USE ASSIGNMENT;
SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;
CREATE TABLE MANAGER (MAN_ID INT PRIMARY KEY, NAME VARCHAR(10));
INSERT INTO MANAGER VALUES(1,'MLN'),(2,'MNZ'),(3,'MNK'),(4,'GYT');

-- JOINS 
SELECT EMPLOYEE.EMPNAME ,DEPARTMENT.DEPTNAME FROM DEPARTMENT JOIN EMPLOYEE ON EMPLOYEE.DEPTID=DEPARTMENT.DEPTID;

SELECT * FROM DEPARTMENT JOIN EMPLOYEE ON EMPLOYEE.DEPTID=DEPARTMENT.DEPTID;

SELECT DEPARTMENT.DEPTID, SUM(EMPLOYEE.SALARY) FROM DEPARTMENT JOIN EMPLOYEE ON EMPLOYEE.DEPTID=DEPARTMENT.DEPTID
GROUP BY DEPARTMENT.DEPTID;

SELECT EMPLOYEE.EMPNAME ,DEPARTMENT.DEPTNAME FROM DEPARTMENT RIGHT OUTER JOIN EMPLOYEE ON EMPLOYEE.DEPTID=DEPARTMENT.DEPTID;

SELECT EMPLOYEE.EMPNAME ,DEPARTMENT.DEPTNAME FROM DEPARTMENT LEFT OUTER JOIN EMPLOYEE ON EMPLOYEE.DEPTID=DEPARTMENT.DEPTID;

SELECT EMPLOYEE.EMPNAME, MANAGER.NAME FROM EMPLOYEE JOIN MANAGER ON EMPLOYEE.MANAGER=MANAGER.MAN_ID;

SELECT EMPLOYEE.EMPNAME,DEPARTMENT.DEPTNAME FROM DEPARTMENT JOIN EMPLOYEE ON EMPLOYEE.DEPTID=DEPARTMENT.DEPTID;


-- UNION
CREATE TABLE EMP1(EMP_ID INT,EMP_NAME VARCHAR(20));
CREATE TABLE EMP2(EMP_ID INT,EMP_NAME VARCHAR(20));
INSERT INTO EMP1 VALUES (1,'A'),(2,'B'),(3,'C');
INSERT INTO EMP1 VALUES (1,'A'),(2,'B'),(4,'D'),(5,'E');

SELECT * FROM EMP1 UNION SELECT * FROM EMP2;
SELECT * FROM EMP1 UNION ALL SELECT * FROM EMP2;

-- SUBQUERY
SELECT EMPNAME FROM EMPLOYEE WHERE SALARY =(SELECT SALARY FROM EMPLOYEE WHERE EMPNAME='Arun')AND EMPNAME NOT LIKE 'Arun';
SELECT EMPNAME FROM EMPLOYEE WHERE DEPTID=(SELECT DEPTID FROM EMPLOYEE WHERE EMPNAME='Jack');
SELECT EMPNAME FROM EMPLOYEE WHERE SALARY =(SELECT MIN(SALARY) FROM EMPLOYEE);
UPDATE  EMPLOYEE SET SALARY=15000  WHERE DEPTID =
 (select DEPTID from(SELECT DEPTID FROM employee  WHERE EMPNAME='Max') as a) and EMPNAME!='Max';


