use assignment;
CREATE TABLE DEPARTMENT (DEPTID INT PRIMARY KEY,DEPTNAME VARCHAR(20));

CREATE TABLE EMPLOYEE(EMPID INT NOT NULL PRIMARY KEY, EMPNAME VARCHAR(20),
 DEPTID INT,SALARY INT,MANAGER INT,
 CONSTRAINT FK FOREIGN KEY (DEPTID) REFERENCES DEPARTMENT(DEPTID));

INSERT INTO DEPARTMENT VALUES (1,'FINANCE'),(2,'TRAINING'),(3,'MARKETING');
INSERT INTO EMPLOYEE VALUES 
(1,'Arun',1,8000,4),
(2,'Kiran',1,7000,1),
(3,'Scott',1,3000,1),
(4,'Max',2,9000,NULL),
(5,'Jack',2	,8000,4),
(6,'King',NULL,6000,1);



SELECT * FROM AUTHORS ORDER BY AUTHOR_NAME ASC;
SELECT * FROM PUBLISHERS ORDER BY PUBLISHER_NAME DESC;

SELECT *,SUM(SALARY) FROM EMPLOYEE GROUP BY DEPTID;
SELECT DEPTID,SUM(SALARY) FROM EMPLOYEE  GROUP BY DEPTID HAVING SUM(SALARY)>17000;
SELECT DEPTID,SUM(SALARY) FROM EMPLOYEE  GROUP BY DEPTID HAVING SUM(SALARY)>18000;
SELECT DEPTID,SUM(SALARY) FROM EMPLOYEE  GROUP BY DEPTID HAVING SUM(SALARY)<20000;

 

	


